### PR TITLE
Documentation: kernel-parameters: Add RISCV for nohlt

### PR DESCRIPTION
**Pull request by bjoto**
Pull request for series with
subject: Documentation: kernel-parameters: Add RISCV for nohlt
version: 1
url: https://patchwork.kernel.org/project/linux-riscv/list/?series=858629

### CODE REVIEW

**Comment by bjoto** [comment]
Upstream branch: 1613e604df0cd359cf2a7fbd9be7a0bcfacfabd0
series: https://patchwork.kernel.org/project/linux-riscv/list/?series=858629
version: 1

**Comment by bjoto** [comment]
Upstream branch: 6d8e604c950260627ba374956e56c3814fa824f9
series: https://patchwork.kernel.org/project/linux-riscv/list/?series=858629
version: 1

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by bjoto** [comment]
Upstream branch: 60a6707f582ebbdfb6b378f45d7bf929106a1cd5
series: https://patchwork.kernel.org/project/linux-riscv/list/?series=858629
version: 1

**Comment by bjoto** [comment]
At least one diff in series https://patchwork.kernel.org/project/linux-riscv/list/?series=858629 irrelevant now. Closing PR.

**Pull request closed without merging**
